Use latest Travis configuration

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,64 +1,130 @@
-# Tell Travis to use new container-based infrastructure
-sudo: false
+# Travis CI (MIT License) configuration file for WP Starter Theme
+# @link https://travis-ci.org/
 
-notifications:
-  email:
-    on_success: never
-    on_failure: change
+# Tell Travis to use new container-based infrastructure.
+sudo: false
 
 # Declare project language.
 # @link http://about.travis-ci.org/docs/user/languages/php/
 language: php
 
-php:
-    - 5.6
-    - 7.0
-
-env:
-    - WP_VERSION=master WP_MULTISITE=0
-    - WP_VERSION=master WP_MULTISITE=1
-
+# Specify when Travis should build.
 branches:
-    only:
-        - master
+  only:
+    - master
 
+cache:
+  directories:
+    - $HOME/.composer/cache
+    - ./vendor
+
+# Git clone depth.
+git:
+  depth: 1
+
+matrix:
+  fast_finish: true
+
+  include:
+    - php: '5.6'
+      env: WP_VERSION=latest PHP_LINT=1
+
+    - php: '7.2'
+      env: WP_VERSION=latest PHP_LINT=1
+    - php: '7.2'
+      env: WP_VERSION=trunk
+    - php: '7.2'
+      env: WP_VERSION=latest WP_PHPCS=1 WP_TRAVIS_OBJECT_CACHE=1
+
+    - php: 'nightly'
+      env: WP_VERSION=latest PHP_LINT=1
+
+  allow_failures:
+    - php: 'nightly'
+
+# Prepare your build for testing.
+# Failures in this section will result in build status 'errored'.
 before_script:
-    # Setup WordPress
-    - export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit
-    - export WP_CORE_DIR=/tmp/wordpress/src/
-    - export WP_DEVELOP_DIR=/tmp/wordpress
-    - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
-    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
-    - cp /tmp/wordpress/wp-tests-config-sample.php /tmp/wordpress/wp-tests-config.php
-    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" /tmp/wordpress/wp-tests-config.php
-    - sed -i "s/yourusernamehere/travis/" /tmp/wordpress/wp-tests-config.php
-    - sed -i "s/yourpasswordhere//" /tmp/wordpress/wp-tests-config.php
+  # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
+  - phpenv config-rm xdebug.ini || echo "Xdebug not available"
 
-    # Install CodeSniffer for WordPress Coding Standards checks.
-    - if [[ "$WP_VERSION" == "master" && "$WP_MULTISITE" == "0" ]]; then git clone -b 2.9 https://github.com/squizlabs/PHP_CodeSniffer.git $WP_DEVELOP_DIR/php-codesniffer; fi;
-    # Install WordPress Coding Standards.
-    - if [[ "$WP_VERSION" == "master" && "$WP_MULTISITE" == "0" ]]; then git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $WP_DEVELOP_DIR/wordpress-coding-standards; fi;
-    # Set install path for WordPress Coding Standards
-    # @link https://github.com/squizlabs/PHP_CodeSniffer/blob/4237c2fc98cc838730b76ee9cee316f99286a2a7/CodeSniffer.php#L1941
-    - if [[ "$WP_VERSION" == "master" && "$WP_MULTISITE" == "0" ]]; then $WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs --config-set installed_paths $WP_DEVELOP_DIR/wordpress-coding-standards; fi;
+  - export PATH="$HOME/.composer/vendor/bin:$PATH"
 
-    # After CodeSniffer install you should refresh your path.
-    - phpenv rehash
+  # Couple the PHPUnit version to the PHP version.
+  - |
+    case "$TRAVIS_PHP_VERSION" in
+    7.2|7.0|nightly)
+      echo "Using PHPUnit 6.1"
+      composer global require "phpunit/phpunit=6.1.*"
+      ;;
+    5.6)
+      echo "Using PHPUnit 4.8"
+      composer global require "phpunit/phpunit=4.8.*"
+      ;;
+    *)
+      echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
+      exit 1
+      ;;
+    esac
+  - og_dir="$(pwd)"
+  - plugin_slug="$(basename $(pwd))"
 
+  - |
+    if [[ ! -z "$WP_VERSION" ]] ; then
+      # Set up the WordPress installation.
+      export WP_CORE_DIR=/tmp/wordpress/
+      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
+      echo "define( 'JETPACK_DEV_DEBUG', true );" >> $WP_CORE_DIR/wp-tests-config.php
+      # Maybe install memcached.
+      if [[ "$WP_TRAVIS_OBJECT_CACHE" == "1" ]]; then
+        curl https://raw.githubusercontent.com/tollmanz/wordpress-pecl-memcached-object-cache/584392b56dc4adbe52bd2c7b86f875e23a3e5f75/object-cache.php > $WP_CORE_DIR/wp-content/object-cache.php
+        echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
+      fi
+      # Set up the plugin. This assumes that this repo name matches the plugin name.
+      mkdir -p "${WP_CORE_DIR}wp-content/plugins/$plugin_slug"
+      cp -R . "${WP_CORE_DIR}wp-content/plugins/$plugin_slug/"
+      # Hop into plugin's directory.
+      cd ${WP_CORE_DIR}wp-content/plugins/$plugin_slug/
+      # For debugging.
+      which phpunit
+      phpunit --version
+    fi
+  # Set up phpcs.
+  - |
+    if [[ "$WP_PHPCS" == "1" ]] ; then
+      composer global require automattic/vipwpcs
+      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/automattic/vipwpcs
+    fi
+  - pwd
+
+# Run test script commands.
+# Default is specific to project language.
+# All commands must exit with code 0 on success. Anything else is considered failure.
 script:
-    # Search for PHP syntax errors.
-    - if [[ "$WP_VERSION" == "master" && "$WP_MULTISITE" == "0" ]]; then find . -type "f" -iname "*.php" | xargs -L "1" php -l; fi;
-
-    # WordPress Coding Standards
-    # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
-    # @link http://pear.php.net/package/PHP_CodeSniffer/
-    # -p flag: Show progress of the run.
-    # -s flag: Show sniff codes in all reports.
-    # -v flag: Print verbose output.
-    # -n flag: Do not print warnings (shortcut for --warning-severity=0)
-    # --standard: Use WordPress as the standard.
-    # --extensions: Only sniff PHP files.
-    - if [[ "$WP_VERSION" == "master" && "$WP_MULTISITE" == "0" ]]; then $WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php; fi;
-
-    # Finally, run PHPUnit
-    - phpunit
+  # Search for PHP syntax errors.
+  #
+  # Only need to run this once per PHP version.
+  - |
+    if [[ "$PHP_LINT" == "1" ]] ; then
+      find . -type "f" -iname "*.php" -not -path "./vendor/*" | xargs -L "1" php -l
+    fi
+  # WordPress Coding Standards.
+  #
+  # These are the same across PHP and WordPress, so we need to run them only once.
+  #
+  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
+  # @link http://pear.php.net/package/PHP_CodeSniffer/
+  - |
+    if [[ "$WP_PHPCS" == "1" ]] ; then
+      phpcs -n
+    fi
+  # Run the theme's unit tests, both in single and multisite.
+  - |
+    if [[ ! -z "$WP_VERSION" ]] ; then
+      phpunit
+      WP_MULTISITE=1 phpunit
+    fi
+# Receive notifications for build results.
+# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
+notifications:
+  email: false
